<a href="https://colab.research.google.com/github/Jetzzza/Tarea-5.-Numpy-y-Matplotlib/blob/main/Tarea_5_Numpy_y_Matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Taller de Herramientas Computacionales

**Tarea 5: Numpy y Matplotlib**

Elaborado por: Miguel Ángel Carrillo Lucía  
Jesús Iván Coss Calderón

# **NUMPY**

**Programar rutinas en Python que hagan lo siguiente:**

In [1]:
import numpy as np

1. Sumas de matrices rectangulares.

2. Multiplicación entrada a entrada de matrices rectangulares.

3. La traza de una matriz.

4. La transpuesta de una matriz.

In [15]:
matriz = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) # Hacer la matriz

filas, columnas = matriz.shape #Sacar el tamaño de la matriz  para la matriz vacía

transpuesta = np.zeros((columnas, filas)) # Crear una matriz vacía con np.zeros para poner la transpuesta

for i in range(filas):
    for j in range(columnas):
        transpuesta[j][i] = matriz[i][j] # Se indica como se tiene que construir la matriz transpuesta intercambiando las filas por las colmnas

print(transpuesta) # Imprimir la matriz transpuesta





[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


5. Encontrar el máximo y mínimo elemento en una matriz.

6. Calcular la suma del cuadrado de los elementos de una matriz.

7. La potencia de matrices.

8.Dadas las matrices A y B:


A =
\begin{pmatrix}
11 & 7 & -1 \\
-3 & 5 & 2 \\
4 & 2 & -2
\end{pmatrix}

B =
\begin{pmatrix}
1 & 1 & 1 \\
10 & 3 & -5 \\
-6 & -10 & -3
\end{pmatrix}



Calcule:

1. 2B + 3A

2.  (B + 2A)^2

3. (A^2 + 3B)



# **MATPLOTLIB**

1. En la clase de ecuaciones diferenciales se pide a los estudiantes encontrar la solución del problema de valor inicial:

y = −y + x

y(−1) = 5

Los estudiantes llegaron a la solución general cuya ecuación es:

y = (x − 1) + Ce^−x

Apoye a sus compañeros y grafique en python la familia de curvas para la solución de la ecuación diferencial y en un sólo gráfico muestre de diferente color las curvas para los siguientes tres casos:

-Para valores de C > 0.

-Cuando C = 0.

-Para valores de C < 0.

Señale en el gráfico las curvas que corresponden a cada uno de los tres casos.

2. Sea la función:

3x + 7 / (x^2) -4

Utilizando la librería matplotlib:

-Grafique la función con línea continua para un rango de -10 a 10, con más de 1000 muestras.

-Investigue en la literatura cómo graficar las asíntotas horizontales y verticales. Muéstrelas en el gráfico con líneas punteadas.

-Defina los límites del eje y para evitar que la gráfica muestre valores muy altos o muy bajos cerca de las asíntotas verticales.

-Añada una leyenda indicando los elementos presentes en la gráfica.